---
namespace: sfey
name: hierarch
version: 1.0.0
readme: README.md
authors:
  - Sasha Fey <fey.sasha@gmail.com>
description: Free software roles for hierarch
license:
  - AGPL-3.0-or-later
license_file: ""
tags: ['application']
dependencies: {}
repository: https://github.com/starshine-bcit/hierarch-collection
documentation: https://github.com/starshine-bcit/hierarch-collection/README.md
homepage: https://hierarch.live
issues: https://github.com/starshine-bcit/hierarch-collection/issues
build_ignore: []
