---
- name: Install orangehrm docker
  become: true
  block:
    - name: Create dir if not exist
      ansible.builtin.file:
        state: directory
        path: "{{ hr_base_dir }}"
        owner: root
        group: root
        mode: '750'
    - name: Copy over docker-compose template
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ hr_base_dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: '640'
    - name: Start docker containers
      community.docker.docker_compose_v2:
        project_src: "{{ hr_base_dir }}"
        state: present
        pull: missing
        files: docker-compose.yml
