---
- name: Setup system environment
  become: true
  block:
    - name: Install necessary packages
      ansible.builtin.apt:
        pkg:
          - postgresql-contrib
          - nodejs
        state: present
        update_cache: true
    - name: Create /srv dir if not exist
      ansible.builtin.file:
        state: directory
        path: /srv
        owner: root
        group: root
        mode: '755'
    - name: Create wikijs system user
      ansible.builtin.user:
        name: wikijs
        home: "{{ wk_home_dir }}"
        system: true
        create_home: false
    - name: Create {{ wk_home_dir }}
      ansible.builtin.file:
        state: directory
        path: "{{ wk_home_dir }}"
        owner: root
        group: wikijs
        mode: '770'
    - name: Create {{ wk_base_dir }}
      ansible.builtin.file:
        state: directory
        path: "{{ wk_base_dir }}"
        owner: root
        group: wikijs
        mode: '770'
    - name: Create data dir
      ansible.builtin.file:
        state: directory
        path: "{{ wk_base_dir }}/data"
        owner: wikijs
        group: root
        mode: '770'
- name: Install and configure wikijs
  become: true
  block:
    - name: Download release archive
      ansible.builtin.get_url:
        url: https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
        dest: "{{ wk_home_dir }}/wiki-js.tar.gz"
        owner: root
        group: wikijs
        mode: '640'
    - name: Extract archive
      ansible.builtin.unarchive:
        src: "{{ wk_home_dir }}/wiki-js.tar.gz"
        dest: "{{ wk_base_dir }}"
        remote_src: true
        owner: root
        group: wikijs
    - name: Copy over config template
      ansible.builtin.template:
        src: config.yml.j2
        dest: "{{ wk_base_dir }}/config.yml"
        owner: root
        group: wikijs
        mode: '640'
    - name: Copy over systemd service
      ansible.builtin.template:
        src: wikijs.service.j2
        dest: "/etc/systemd/system/wikijs.service"
        owner: root
        group: root
        mode: '644'
    - name: Start/Restart systemd service
      ansible.builtin.systemd_service:
        name: wikijs
        state: restarted
        enabled: true
        daemon_reload: true
