---
- name: Setup system environment
  become: true
  block:
    - name: Install necessary system packages
      ansible.builtin.apt:
        pkg:
          - postgresql
          - libpq-dev
          - python3-psycopg2
          - openssl
          - acl
        update_cache: true
- name: Loop over provided DB configurations
  ansible.builtin.include_tasks: db_config.yml
  loop: "{{ db_databases }}"
  no_log: true
- name: Copy certs and configure config files for postgres
  become: true
  become_user: root
  block:
    - name: Copy letsencrypt cert file
      ansible.builtin.copy:
        remote_src: true
        src: "{{ postgres_remote_cert_file }}"
        dest: "{{ postgres_local_cert_file }}"
        owner: postgres
        group: postgres
        mode: '400'
    - name: Copy letsencrypt key file
      ansible.builtin.copy:
        remote_src: true
        src: "{{ postgres_remote_key_file }}"
        dest: "{{ postgres_local_key_file }}"
        owner: postgres
        group: postgres
        mode: '400'
    - name: Change ssl_cert_file config line
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^ssl_cert_file"
        backrefs: true
        line: "ssl_cert_file = '{{ postgres_local_cert_file }}'"
    - name: Change ssl_key_file config line
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^ssl_key_file"
        backrefs: true
        line: "ssl_key_file = '{{ postgres_local_key_file }}'"
    - name: Set listen address to all
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "listen_addresses = 'localhost'"
        backrefs: true
        line: "listen_addresses = '*'"
      when: not db_is_local
    - name: Set listen address to localhost
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "listen_addresses = '*'"
        backrefs: true
        line: "listen_addresses = 'localhost'"
      when: db_is_local
    - name: Change ssl config line
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?ssl\ ='
        backrefs: true
        line: "ssl = on"
    - name: Restart postgres
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
        enabled: true
    - name: Rebuild post-renewal hook
      ansible.builtin.template:
        src: post_hook.j2
        dest: /etc/letsencrypt/renewal-hooks/post/start_services
        owner: root
        group: root
        mode: '750'
