---
- name: Setup system environment
  become: true
  block:
    - name: Install necessary system packages
      ansible.builtin.apt:
        pkg:
          - postgresql
          - libpq-dev
          - python3-psycopg2
          - openssl
          - acl
        update_cache: true
- name: Configure keycloak postgres
  become: true
  become_user: postgres
  block:
    - name: Create new database "{{ kc_db_name }}"
      community.postgresql.postgresql_db:
        name: "{{ kc_db_name }}"
        encoding: UTF-8
    - name: Create new database forgejo
      community.postgresql.postgresql_db:
        name: forgejo
        encoding: UTF-8
    - name: Add new user "{{ kc_db_user }}"
      community.postgresql.postgresql_user:
        db: "{{ kc_db_name }}"
        user: "{{ kc_db_user }}"
        password: "{{ kc_db_pass }}"
        expires: "Infinity"
    - name: Add new user "{{ fj_db_user }}"
      community.postgresql.postgresql_user:
        db: forgejo
        user: "{{ fj_db_user }}"
        password: "{{ fj_db_pass }}"
        expires: "Infinity"
    - name: Create new schema keycloak
      community.postgresql.postgresql_schema:
        db: "{{ kc_db_name }}"
        name: keycloak
        owner: postgres
    - name: Create new schema forgejo
      community.postgresql.postgresql_schema:
        db: forgejo
        name: forgejo
        owner: postgres
    - name: Grant schema privs
      community.postgresql.postgresql_privs:
        db: "{{ kc_db_name }}"
        state: present
        priv: ALL
        type: schema
        objs: keycloak
        role: "{{ kc_db_user }}"
    - name: Grant schema privs
      community.postgresql.postgresql_privs:
        db: forgejo
        state: present
        priv: ALL
        type: schema
        objs: forgejo
        role: "{{ fj_db_user }}"
    - name: Reassign ownership of db to "{{ kc_db_user }}"
      community.postgresql.postgresql_owner:
        db: "{{ kc_db_name }}"
        new_owner: "{{ kc_db_user }}"
    - name: Reassign ownership of forgejo db
      community.postgresql.postgresql_owner:
        db: forgejo
        new_owner: "{{ fj_db_user }}"
    - name: Setup permissions for "{{ kc_db_user }}"
      community.postgresql.postgresql_privs:
        db: postgres
        state: present
        privs: ALL
        role: "{{ kc_db_user }}"
        type: database
        obj: "{{ kc_db_name }}"
        grant_option: false
    - name: Setup permissions for forgejo user
      community.postgresql.postgresql_privs:
        db: postgres
        state: present
        privs: ALL
        role: "{{ fj_db_user }}"
        type: database
        obj: forgejo
        grant_option: false
    - name: Configure localhost pg_hba for "{{ kc_db_user }}"
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/15/main/pg_hba.conf
        databases: "{{ kc_db_name }}"
        contype: local
        users: "{{ kc_db_user }}"
        method: scram-sha-256
        mode: "640"
        group: postgres
        owner: postgres
      when: kc_db_origin == "127.0.0.1"
    - name: Configure remote pg_hba for "{{ kc_db_user }}"
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/15/main/pg_hba.conf
        databases: "{{ kc_db_name }}"
        contype: host
        address: "{{ kc_db_origin }}"
        users: "{{ kc_db_user }}"
        method: scram-sha-256
        mode: "640"
        group: postgres
        owner: postgres
      when: kc_db_origin != "127.0.0.1"
    - name: Configure remote pg_hba for forgejo
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/15/main/pg_hba.conf
        databases: forgejo
        contype: host
        address: "{{ hostvars['app01'].ansible_host }}"
        users: "{{ fj_db_user }}"
        method: scram-sha-256
        mode: "640"
        group: postgres
        owner: postgres
    - name: Copy letsencrypt cert file
      ansible.builtin.copy:
        remote_src: true
        src: "{{ postgres_remote_cert_file }}"
        dest: "{{ postgres_local_cert_file }}"
        owner: postgres
        group: postgres
        mode: '400'
      become: true
      become_user: root
    - name: Copy letsencrypt key file
      ansible.builtin.copy:
        remote_src: true
        src: "{{ postgres_remote_key_file }}"
        dest: "{{ postgres_local_key_file }}"
        owner: postgres
        group: postgres
        mode: '400'
      become: true
      become_user: root
    - name: Change ssl_cert_file config line
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^ssl_cert_file"
        backrefs: true
        line: "ssl_cert_file = '{{ postgres_local_cert_file }}'"
    - name: Change ssl_key_file config line
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^ssl_key_file"
        backrefs: true
        line: "ssl_key_file = '{{ postgres_local_key_file }}'"
    - name: Change ssl config line
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?ssl\ ='
        backrefs: true
        line: "ssl = on"
    - name: Restart postgres
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
      become: true
      become_user: root
    - name: Rebuild post-renewal hook
      ansible.builtin.template:
        src: post_hook.j2
        dest: /etc/letsencrypt/renewal-hooks/post/start_services
        owner: root
        group: root
        mode: '750'
      become: true
      become_user: root
